sudo: required
language: generic
dist: xenial
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - avishaya@amazon.com
env:
  global:
  - SA_NAME=hello-world
  - SA_PACKAGE_NAME=hello_world_robot
  - NO_TEST=true
  - GH_USER_NAME="travis-ci"
  - GH_USER_EMAIL="travis@travis-ci.org"
  - AWS_DEFAULT_REGION=us-west-2
before_install:
- pip install --user awscli
install:
- git clone https://github.com/aws-robotics/travis-scripts.git .ros_ci
script:
- . .ros_ci/add_tag.sh && set +e
- while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
- ".ros_ci/ce_build.sh"
- kill %1
before_deploy:
- . .ros_ci/before_deploy.sh && set +e
deploy:
  - provider: s3
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
    bucket: "$S3_BUCKET_NAME"
    region: "us-west-2"
    local_dir: shared
    skip_cleanup: true
    wait-until-deployed: true
    on:
      branch: ros2
    upload-dir: travis/${SA_NAME}/${ROS_DISTRO}/gazebo${GAZEBO_VERSION}
jobs:
  include:
     - stage: Upload sources
       env: ROS_VERSION=2 WORKSPACES="robot_ws simulation_ws"
       script: . .ros_ci/add_tag.sh && . .ros_ci/upload_sources.sh && ls shared && set +e
    #- stage: Build & Bundle
    #  env: ROS_DISTRO=dashing ROS_VERSION=2 GAZEBO_VERSION=9 WORKSPACES="robot_ws"
    #- stage: Build & Bundle
    #  env: ROS_DISTRO=dashing ROS_VERSION=2 GAZEBO_VERSION=9 WORKSPACES="simulation_ws"
    #- stage: Deploy
    #  script: ". .ros_ci/add_tag.sh"
    #  env: ROS_DISTRO=dashing ROS_VERSION=2 GAZEBO_VERSION=9
    #  before_deploy: "export APP_MANIFEST_REPO=AppManifest-${SA_NAME}-${ROS_DISTRO}-gazebo${GAZEBO_VERSION}"
    #  deploy:
    #    - provider: script
    #      script: bash .ros_ci/codepipeline_deploy.sh
    #      on:
    #        branch: ros2
after_deploy:
- .ros_ci/post_deploy.sh
